name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0
  mobile_scanner: ^4.0.0
  intl: ^0.18.0
  shared_preferences: ^2.2.0
  device_info_plus: ^9.1.0
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logoIcon.png"
  adaptive_icon_background: "#0A0E14"
  adaptive_icon_foreground: "assets/logoIcon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#0A0E14"
  image: assets/logo.png
  android: true
  ios: true
  android_12:
    color: "#0A0E14"
    image: assets/logo.png
    
flutter:
  uses-material-design: true

  assets:
    - assets/
